const { withInfoPlist, withAppDelegate, IOSConfig } = require('@expo/config-plugins');

// iOS now hard-enforces UIScene adoption: an app with no UIApplicationSceneManifest
// gets killed at launch with EXC_BREAKPOINT / "NoSceneLifecycleAdoption". Expo's
// template still ships the pre-scenes AppDelegate-only lifecycle, so this plugin
// adds a minimal single-window SceneDelegate and wires it up. We stay single-scene
// (UIApplicationSupportsMultipleScenes: false) — this isn't opting into multi-window,
// just satisfying the OS requirement while keeping current behavior.

const SCENE_DELEGATE_CLASS_NAME = 'SceneDelegate';

const SCENE_DELEGATE_SWIFT = `import UIKit
import React

// Owns the app's single window under the scene lifecycle. RN bootstrapping used
// to happen in AppDelegate.didFinishLaunchingWithOptions; it moved here because a
// UIWindow now needs a UIWindowScene to attach to. Generated by
// plugins/withSceneDelegate.js — do not hand-edit, it will be overwritten on
// the next prebuild.
class ${SCENE_DELEGATE_CLASS_NAME}: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let windowScene = scene as? UIWindowScene else { return }
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate,
          let factory = appDelegate.reactNativeFactory else { return }

    let window = UIWindow(windowScene: windowScene)
    factory.startReactNative(withModuleName: "main", in: window, launchOptions: nil)

    self.window = window
    appDelegate.window = window

    if let urlContext = connectionOptions.urlContexts.first {
      _ = RCTLinkingManager.application(UIApplication.shared, open: urlContext.url, options: [:])
    }
    if let userActivity = connectionOptions.userActivities.first {
      _ = RCTLinkingManager.application(UIApplication.shared, continue: userActivity, restorationHandler: { _ in })
    }
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let url = URLContexts.first?.url else { return }
    _ = RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = RCTLinkingManager.application(UIApplication.shared, continue: userActivity, restorationHandler: { _ in })
  }
}
`;

const WINDOW_BOOTSTRAP_BLOCK = `
#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif
`;

const SCENE_CONFIGURATION_METHOD = `
  // Added by plugins/withSceneDelegate.js: tells UIKit which scene delegate
  // owns the window. Required for UIApplicationSceneManifest adoption.
  public func application(
    _ application: UIApplication,
    configurationForConnecting connectingSceneSession: UISceneSession,
    options: UIScene.ConnectionOptions
  ) -> UISceneConfiguration {
    let configuration = UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
    configuration.delegateClass = ${SCENE_DELEGATE_CLASS_NAME}.self
    return configuration
  }
`;

function withSceneManifest(config) {
  return withInfoPlist(config, (config) => {
    config.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: `$(PRODUCT_MODULE_NAME).${SCENE_DELEGATE_CLASS_NAME}`,
          },
        ],
      },
    };
    return config;
  });
}

function withSceneDelegateSource(config) {
  return IOSConfig.XcodeProjectFile.withBuildSourceFile(config, {
    filePath: `${SCENE_DELEGATE_CLASS_NAME}.swift`,
    contents: SCENE_DELEGATE_SWIFT,
    overwrite: true,
  });
}

function withAppDelegateSceneSupport(config) {
  return withAppDelegate(config, (config) => {
    let contents = config.modResults.contents;

    // Window creation moved to SceneDelegate — drop it here if still present
    // (idempotent: no-op once already removed).
    if (contents.includes(WINDOW_BOOTSTRAP_BLOCK)) {
      contents = contents.replace(WINDOW_BOOTSTRAP_BLOCK, '');
    }

    // Register the scene configuration once.
    if (!contents.includes('configurationForConnecting')) {
      const marker = '  // Linking API';
      if (!contents.includes(marker)) {
        throw new Error(
          'withSceneDelegate: expected marker "// Linking API" not found in AppDelegate.swift — Expo\'s template must have changed, update plugins/withSceneDelegate.js.'
        );
      }
      contents = contents.replace(marker, `${SCENE_CONFIGURATION_METHOD}\n${marker}`);
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = function withSceneDelegate(config) {
  config = withSceneManifest(config);
  config = withSceneDelegateSource(config);
  config = withAppDelegateSceneSupport(config);
  return config;
};
